import type { Metadata } from 'next'
import { Outfit } from 'next/font/google'
import './globals.css'

//Components
import Navbar from '@/shared/components/Navbar'

const outfit = Outfit({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Cars Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${outfit.className} antialiased`}>
				<Navbar />
				{children}
			</body>
		</html>
	)
}
